version: '3.2'   # .ymlフォーマットのバージョン

services:
  python:
    image: python/ubuntu:1.0
    build: .     # Dockerfileの場所
    container_name: 'container'
    working_dir: '/work'
    volumes: 
      - ../work:/work
      - ../../images:/work/dataset/data/images        # 左がローカルファイルの場所
      - ../../original:/work/dataset/data/original

      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment: 
      - DISPLAY=${DISPLAY}
    devices: 
      - /dev/video0:/dev/video0:mwr
    stdin_open: true
    tty: true
    privileged: true
    
    
    
